# Generated by Django 3.2 on 2021-12-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='credit',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
