# Generated by Django 3.2 on 2022-01-07 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_faculty_student_details_student_hostel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0002_subject_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='faculty_handled_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='main_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(blank=True, max_length=50, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dept_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.department')),
                ('subjects', models.ManyToManyField(through='academic.class_subject', to='academic.subject')),
            ],
        ),
        migrations.CreateModel(
            name='registered_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='sub_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher', to=settings.AUTH_USER_MODEL)),
                ('parent_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.main_class')),
                ('students', models.ManyToManyField(through='academic.registered_students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='student_class',
            name='dept_id',
        ),
        migrations.RemoveField(
            model_name='student_class',
            name='students',
        ),
        migrations.RemoveField(
            model_name='subject_handler',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='subject_handler',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='subject_handler',
            name='subject_id',
        ),
        migrations.RemoveField(
            model_name='subject_student_enrollment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='subject_student_enrollment',
            name='subject_id',
        ),
        migrations.DeleteModel(
            name='class_member',
        ),
        migrations.DeleteModel(
            name='student_class',
        ),
        migrations.DeleteModel(
            name='subject_handler',
        ),
        migrations.DeleteModel(
            name='subject_student_enrollment',
        ),
        migrations.AddField(
            model_name='registered_students',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.sub_class'),
        ),
        migrations.AddField(
            model_name='registered_students',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faculty_handled_class',
            name='sub_class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.sub_class'),
        ),
        migrations.AddField(
            model_name='faculty_handled_class',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class_subject'),
        ),
        migrations.AddField(
            model_name='class_subject',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.main_class'),
        ),
        migrations.AddField(
            model_name='class_subject',
            name='class_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.subject'),
        ),
    ]
