# Generated by Django 3.2 on 2022-01-08 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0003_auto_20220107_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendence_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('sclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.sub_class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.faculty_handled_class')),
            ],
        ),
        migrations.CreateModel(
            name='attendence_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_class', models.IntegerField(default=0)),
                ('attended_class', models.IntegerField(default=0)),
                ('sclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.sub_class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.faculty_handled_class')),
            ],
        ),
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.attendence_schedule')),
            ],
        ),
    ]
