# Generated by Django 3.2 on 2022-01-11 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0004_attendence_attendence_count_attendence_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_type',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('max_marks', models.IntegerField(blank=True, default=10, null=True)),
                ('pass_marks', models.IntegerField(blank=True, default=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.sub_class')),
                ('subject_handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.faculty_handled_class')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class_subject')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.test_type')),
            ],
        ),
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.test')),
            ],
        ),
    ]
