# Generated by Django 3.2 on 2022-01-12 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_days_time_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_table',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.days'),
        ),
    ]
