# Generated by Django 3.2 on 2022-01-12 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_time_table_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_table',
            name='sclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.sub_class'),
        ),
    ]
