# Generated by Django 3.2 on 2021-12-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user_status',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
