# Generated by Django 3.2 on 2021-12-19 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('info', '0006_alter_designation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField(blank=True, null=True)),
                ('hostel_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.hostel')),
                ('student_adm_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('adm_no', models.IntegerField(blank=True, null=True)),
                ('usn', models.CharField(blank=True, max_length=15, null=True)),
                ('current_year', models.IntegerField(blank=True, null=True)),
                ('year_of_joining', models.IntegerField(blank=True, null=True)),
                ('year_of_passout', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=50, null=True)),
                ('student_phone_number', models.IntegerField(blank=True, null=True)),
                ('parent_phone_number', models.IntegerField(blank=True, null=True)),
                ('student_mail', models.EmailField(blank=True, max_length=50, null=True)),
                ('parent_mail', models.EmailField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('dept_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.department')),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('year_of_joining', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('dept_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_id', to=settings.AUTH_USER_MODEL)),
                ('designation_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designation_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
