# Generated by Django 3.2.5 on 2021-12-08 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0006_alter_designation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_personal_details',
            fields=[
                ('adm_no', models.IntegerField(primary_key=True, serialize=False)),
                ('dob', models.DateField(max_length=10)),
                ('gender', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('guardian_name', models.CharField(max_length=50)),
                ('student_phone_number', models.IntegerField()),
                ('student_mail', models.EmailField(max_length=50)),
                ('parent_mail', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='student_hostel',
            fields=[
                ('student_adm_no', models.IntegerField(primary_key=True, serialize=False)),
                ('room_no', models.IntegerField()),
                ('hostel_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('adm_no', models.IntegerField(primary_key=True, serialize=False)),
                ('usn', models.CharField(max_length=15)),
                ('current_year', models.IntegerField()),
                ('year_of_joining', models.IntegerField()),
                ('year_of_passout', models.IntegerField()),
                ('dept_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dep_id', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('dob', models.DateField(max_length=10)),
                ('gender', models.CharField(max_length=20)),
                ('year_of_joining', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('dept_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_id', to=settings.AUTH_USER_MODEL)),
                ('designation_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designation_id', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
