# Generated by Django 3.2 on 2022-01-12 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_faculty_student_details_student_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='new_dept',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.department'),
        ),
    ]
