# Generated by Django 3.2 on 2022-01-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_faculty_new_dept'),
    ]

    operations = [
        migrations.DeleteModel(
            name='faculty',
        ),
    ]
